#  Calculation of features from available libraries

- input curated BS

TODO: MUST: include SOAP ! SOAP from matminer and dscribe wont work, apparently. retunrs None!

In [1]:
import sys
sys.path.insert(0, '/home/storage/fortimtb/DatasetsML/Tools/')
sys.path.insert(0, '/home/storage/fortimtb/CuadernoTrabajo/bopfoxfeaturizer/')

DATASET = 'Cr-Co-W'
from GetPymatgenFeatures import *
from BopFoxFeaturizer.Featurizer import Featurizer

mmflatomic = os.path.join(case,'matminer_atomic_features.pkl')
mmfdensity = os.path.join (case, 'matminer_density_features.pkl')
mmfcomposition =  os.path.join (case,'matminer_composition_features.pkl')
mmfstructure =  os.path.join (case,'matminer_structure_features.pkl')
mmsoapfeatures = os.path.join(case, 'matminer_soap_features.pkl')

BS = pd.read_pickle('CuratedParsedBriefSummary.pkl')
BS['atoms_objects'] = pd.read_pickle('CrCoW-sorted-POSCAR-initial-rescaled-PymatgenStructures.pkl').dropna()
BS.dropna(inplace=True)

BS['chemical_formula'] = get_chemical_formula(BS)

# Matminer Features

In [2]:
BS['composition'] = StrToComposition().featurize_dataframe(BS, "chemical_formula")['composition']

StrToComposition:   0%|          | 0/1665 [00:00<?, ?it/s]

In [3]:
AtomicFeaturesMagpie = load_features(mmflatomic, BS, which='atomic')
DensitiFeatures= load_features(mmfdensity, BS, which='density')
CompositionFeatures = load_features(mmfcomposition, BS, which='composition')
SOAPFeatures = load_features(mmfstructure, BS, which='soap')
# SOAP doesnt work from matminer

In [4]:
StructureFeatures = load_features(mmfstructure, BS, which='structure')

In [5]:
StructureFeatures.dropna(axis=1)

                                    max packing efficiency
Co_pv6W_sv6.C14-BBA.NM                            0.647623
Co_pv6W_sv6.C14-BBA.FM                            0.647623
Cr_pv6W_sv2.D0_19-A3B.FM                          0.712095
Cr_pv6W_sv2.D0_19-A3B.NM                          0.712095
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM                0.584180
...                                                    ...
Cr_pv10W_sv3.mu-BAAAB.FM                          0.634381
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM                 0.584180
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM                 0.584180
Co_pv13W_sv16.chi-ABAB.NM                         0.565533
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM                0.584180

[1665 rows x 1 columns]

In [6]:
AtomicFeaturesMagpie.columns = AtomicFeaturesMagpie.columns.str.replace('MagpieData ','')

In [7]:
AtomicFeaturesMagpie.dropna(axis=1, inplace = True)

In [8]:
AtomicFeaturesMagpie.describe()

,minimum Number,maximum Number,range Number,mean Number,avg_dev Number,mode Number,minimum MendeleevNumber,maximum MendeleevNumber,range MendeleevNumber,mean MendeleevNumber,...,range GSmagmom,mean GSmagmom,avg_dev GSmagmom,mode GSmagmom,minimum SpaceGroupNumber,maximum SpaceGroupNumber,range SpaceGroupNumber,mean SpaceGroupNumber,avg_dev SpaceGroupNumber,mode SpaceGroupNumber
count,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,...,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.00000,1665.000000,1665.000000,1665.000000
mean,24.894895,67.363964,42.469069,46.695370,13.387501,47.036036,49.366967,56.857057,7.490090,52.778750,...,1.284348,0.500626,0.420920,0.468726,199.612613,228.642643,29.03003,217.684378,9.514019,217.081081
std,4.947841,16.417982,16.882773,15.824360,8.449581,24.003804,1.115015,2.623395,2.748698,2.128762,...,0.582607,0.445878,0.277748,0.711624,12.846756,3.519552,13.16862,10.078151,6.277913,16.591168
min,24.000000,24.000000,0.000000,24.000000,0.000000,24.000000,49.000000,49.000000,0.000000,49.000000,...,0.000000,0.000000,0.000000,0.000000,194.000000,194.000000,0.00000,194.000000,0.000000,194.000000
25%,24.000000,74.000000,47.000000,33.307692,5.859375,27.000000,49.000000,58.000000,7.000000,51.106061,...,1.548471,0.119113,0.181461,0.000000,194.000000,229.000000,35.00000,212.666667,4.101562,194.000000
50%,24.000000,74.000000,50.000000,44.615385,13.583829,27.000000,49.000000,58.000000,9.000000,52.166667,...,1.548471,0.387118,0.430131,0.000000,194.000000,229.000000,35.00000,220.250000,9.722222,229.000000
75%,24.000000,74.000000,50.000000,62.461538,21.555556,74.000000,49.000000,58.000000,9.000000,53.923077,...,1.548471,0.722620,0.688209,1.548471,194.000000,229.000000,35.00000,226.307692,15.555556,229.000000
max,74.000000,74.000000,50.000000,74.000000,24.793388,74.000000,58.000000,58.000000,9.000000,58.000000,...,1.548471,1.548471,0.774236,1.548471,229.000000,229.000000,35.00000,229.000000,17.500000,229.000000

In [9]:
DensitiFeatures.dropna(axis=1, inplace=True)

In [10]:
DensitiFeatures.describe()

           density          vpa  packing fraction
count  1665.000000  1665.000000       1665.000000
mean     15.287521    10.701618          0.998829
std       5.087256     0.407380          0.033768
min       0.649612     2.576499          0.025403
25%      11.429203    10.488771          1.000000
50%      14.675017    10.702010          1.000000
75%      18.784192    10.939619          1.000000
max      29.620964    11.494040          1.000000

In [11]:
CompositionFeatures.dropna(axis=1, inplace=True)

In [12]:
CompositionFeatures.describe()

,HOMO_energy,LUMO_energy,gap_AO,band center,max ionic char,avg ionic char,0-norm,2-norm,3-norm,5-norm,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
count,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,...,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.00000,1665.000000,1665.000000,1665.000000
mean,-0.207912,-0.206902,0.001010,4.185060,0.091838,0.012615,2.551351,0.755231,0.713343,0.693194,...,1.284348,0.500626,0.420920,0.468726,199.612613,228.642643,29.03003,217.684378,9.514019,217.081081
std,0.050215,0.051056,0.005883,0.147703,0.039763,0.008042,0.554624,0.137855,0.169035,0.187124,...,0.582607,0.445878,0.277748,0.711624,12.846756,3.519552,13.16862,10.078151,6.277913,16.591168
min,-0.322368,-0.322368,0.000000,3.716833,0.000000,0.000000,1.000000,0.584998,0.493242,0.435713,...,0.000000,0.000000,0.000000,0.000000,194.000000,194.000000,0.00000,194.000000,0.000000,194.000000
25%,-0.220603,-0.220603,0.000000,4.080115,0.055973,0.004929,2.000000,0.628932,0.563224,0.530175,...,1.548471,0.119113,0.181461,0.000000,194.000000,229.000000,35.00000,212.666667,4.101562,194.000000
50%,-0.220603,-0.220603,0.000000,4.199398,0.115294,0.013709,3.000000,0.707107,0.673540,0.651528,...,1.548471,0.387118,0.430131,0.000000,194.000000,229.000000,35.00000,220.250000,9.722222,229.000000
75%,-0.181413,-0.181413,0.000000,4.298091,0.115294,0.019364,3.000000,0.897130,0.890964,0.890416,...,1.548471,0.722620,0.688209,1.548471,194.000000,229.000000,35.00000,226.307692,15.555556,229.000000
max,-0.118123,-0.118123,0.054052,4.397803,0.115294,0.028585,3.000000,1.000000,1.000000,1.000000,...,1.548471,1.548471,0.774236,1.548471,229.000000,229.000000,35.00000,229.000000,17.500000,229.000000

In [13]:
SOAPFeatures.dropna(axis=1)

                                    max packing efficiency
Co_pv6W_sv6.C14-BBA.NM                            0.647623
Co_pv6W_sv6.C14-BBA.FM                            0.647623
Cr_pv6W_sv2.D0_19-A3B.FM                          0.712095
Cr_pv6W_sv2.D0_19-A3B.NM                          0.712095
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM                0.584180
...                                                    ...
Cr_pv10W_sv3.mu-BAAAB.FM                          0.634381
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM                 0.584180
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM                 0.584180
Co_pv13W_sv16.chi-ABAB.NM                         0.565533
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM                0.584180

[1665 rows x 1 columns]

## Some extra info like magnetic configuration and know crystal structure

In [14]:
Features = Featurizer(BS)
BS['Mag'] = Features.Mag[BS.index].map(make_magnetic_feature)

In [15]:
CompositionFeatures = pd.concat([CompositionFeatures, Features.get_fractions_by_components()], axis =1 )