In [1]:
from importlib.machinery import SourceFileLoader
import pandas as pd

In [2]:
%run GetPymatgenFeatures.py

StrToComposition:   0%|          | 0/1687 [00:00<?, ?it/s]

MultipleFeaturizer:   0%|          | 0/1687 [00:00<?, ?it/s]

AttributeError: 'NoneType' object has no attribute 'columns'

In [3]:
from SourceDevelopementVersion import Featurizer, FeatureConcatenate

In [4]:
from TernaryPlot import get_fractions_by_components
components = ['Co','Cr','W']
BS[components] = get_fractions_by_components(BS, components)

In [5]:
BS[components]

                                          Co        Cr         W
index
Co_pv6W_sv6.C14-BBA.FM              0.500000  0.000000  0.500000
Co_pv6W_sv6.C14-BBA.NM              0.500000  0.000000  0.500000
Cr_pv6W_sv2.D0_19-A3B.FM            0.000000  0.750000  0.250000
Cr_pv6W_sv2.D0_19-A3B.NM            0.000000  0.750000  0.250000
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM  0.133333  0.533333  0.333333
...                                      ...       ...       ...
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM   0.066667  0.666667  0.266667
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM   0.066667  0.666667  0.266667
Co_pv13W_sv16.chi-ABAB.NM           0.448276  0.000000  0.551724
Co_pv13W_sv16.chi-ABAB.FM           0.448276  0.000000  0.551724
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM  0.133333  0.533333  0.333333

[1687 rows x 3 columns]

In [6]:
BS = pd.read_pickle('parsedbs.pkl')
Features = Featurizer(BS)
groundstates = Features.get_ground_states_energies()
BS['EF'] = Features.get_formation_energy(groundstates)

In [7]:
def make_magnetic_feature(MagInfo):
    if MagInfo == 'NM':
        return 0
    elif MagInfo == 'NM':
        return 1
    else:
        return 2

In [8]:
BS['Mag'] = Features.Mag[BS.index].map(make_magnetic_feature)

In [9]:
BS.columns

Index(['', 'B', 'E0', 'V', 'deltak', 'encut', 'fit', 'ncrash', 'nelem', 'xc',
       'B0', 'V0', 'atom_A', 'atom_B', 'atom_C', 'num_atom_A', 'num_atom_B',
       'num_atom_C', 'num_atoms', 'EF', 'Mag'],
      dtype='object')

In [10]:
AllFeatures = pd.concat([AtomicFeaturesMagpie, DensitiFeatures, CompositionFeatures,BS[['Mag','nelem','num_atoms']]], axis = 1)

In [11]:
search_to_drop = AllFeatures.columns.str.contains('range|min|max')
columns_to_drop = AllFeatures.loc[:,search_to_drop].columns
AllFeatures.drop(columns=columns_to_drop, inplace=True)

In [12]:
AllFeatures

,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData mean MendeleevNumber,MagpieData avg_dev MendeleevNumber,MagpieData mode MendeleevNumber,MagpieData mean AtomicWeight,MagpieData avg_dev AtomicWeight,MagpieData mode AtomicWeight,MagpieData mean MeltingT,...,avg ionic char,0-norm,2-norm,3-norm,5-norm,7-norm,10-norm,Mag,nelem,num_atoms
index,,,,,,,,,,,,,,,,,,,,,
Co_pv6W_sv6.C14-BBA.FM,69.727273,7.768595,74.0,51.636364,1.157025,51.0,172.484836,20.645753,183.8400,3519.818182,...,0.004626,2,0.913625,0.909394,0.909093,0.909091,0.909091,2,2,12.0
Co_pv6W_sv6.C14-BBA.NM,69.727273,7.768595,74.0,51.636364,1.157025,51.0,172.484836,20.645753,183.8400,3519.818182,...,0.004626,2,0.913625,0.909394,0.909093,0.909091,0.909091,0,2,12.0
Cr_pv6W_sv2.D0_19-A3B.FM,62.461538,17.751479,74.0,50.538462,0.710059,51.0,153.414485,46.808485,183.8400,3345.384615,...,0.020466,2,0.803101,0.776092,0.769604,0.769255,0.769231,2,2,8.0
Cr_pv6W_sv2.D0_19-A3B.NM,62.461538,17.751479,74.0,50.538462,0.710059,51.0,153.414485,46.808485,183.8400,3345.384615,...,0.020466,2,0.803101,0.776092,0.769604,0.769255,0.769231,0,2,8.0
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM,41.066667,21.955556,24.0,50.866667,1.991111,49.0,96.869013,57.980658,51.9961,2630.066667,...,0.023840,3,0.642910,0.576008,0.543235,0.536132,0.533816,2,3,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM,37.533333,19.448889,24.0,50.133333,1.511111,49.0,87.616946,51.318962,51.9961,2556.533333,...,0.022026,3,0.721110,0.680809,0.668028,0.666823,0.666674,2,3,30.0
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM,37.533333,19.448889,24.0,50.133333,1.511111,49.0,87.616946,51.318962,51.9961,2556.533333,...,0.022026,3,0.721110,0.680809,0.668028,0.666823,0.666674,0,3,30.0
Co_pv13W_sv16.chi-ABAB.NM,70.468208,6.532794,74.0,51.526012,0.972969,51.0,174.453940,17.361499,183.8400,3550.196532,...,0.003890,2,0.927903,0.925021,0.924856,0.924855,0.924855,0,2,29.0
Co_pv13W_sv16.chi-ABAB.FM,70.468208,6.532794,74.0,51.526012,0.972969,51.0,174.453940,17.361499,183.8400,3550.196532,...,0.003890,2,0.927903,0.925021,0.924856,0.924855,0.924855,2,2,29.0
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM,41.066667,21.955556,24.0,50.866667,1.991111,49.0,96.869013,57.980658,51.9961,2630.066667,...,0.023840,3,0.642910,0.576008,0.543235,0.536132,0.533816,0,3,30.0

In [13]:
AllFeatures.dropna(inplace=True)

In [14]:
#to_remove =  AllFeatures.columns.str.contains('Np|Nf|mode Number|mode Mendeleev|Row|mode Nd|mode')
#AllFeatures.drop(columns=AllFeatures.columns[to_remove],inplace=True)

In [15]:
bestfeats = {}
bestscores = {}
FC = {}

In [16]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(AllFeatures, BS['EF'].loc[AllFeatures.index])

In [18]:
CASE = 'initial'
criterion = 'train_score'

In [19]:
del FeatureConcatenate
FeatureConcatenate = SourceFileLoader('FeatureConcate','/home/storage/fortimtb/CuadernoTrabajo/bopfoxfeaturizer/BopFoxFeaturizer/FeatureConcatenate.py'
                                     ).load_module().FeatureConcatenate

param_grid = {} 
Bestfeatsatomic = {} 
Bestscoresatomic = {}
FC['RandomForest_atomic'] = FeatureConcatenate(
    pd.concat([X_train, Y_train], axis=1), #DATA, 
    RandomForestRegressor(),
    model_params=param_grid,
    feature_list=AllFeatures.columns,
    data_target='EF',
    criterion = criterion
#    sample_weights = w_train, #Classes['Weights']
)

Bestfeatsatomic['RandomForest_atomic'], Bestscoresatomic['RandomForest_atomic'] = FC['RandomForest_atomic'].build_features_list(
#    best_feature_proposal=['NSC_bn_1'],
    pass_force_refit=True,
    report_prefix='RandomForest_atomic_'+CASE,
)

procesing '[]' with 'nelem' ... ::   0%|                                                         | 0/83 [00:00<?, ?it/s]

Refitting ..

procesing '[]' with 'HOMO_energy' ... :: 100%|##########################################| 83/83 [01:05<00:00,  1.26it/s]

fitting has finished

procesing '['density']' with 'nelem' ... ::   0%|                                                | 0/57 [00:00<?, ?it/s]

Refitting ..

procesing '['density']' with 'HOMO_energy' ... :: 100%|#################################| 57/57 [00:58<00:00,  1.03s/it]

fitting has finished

procesing '['density', 'num_atoms']' with 'nelem' ... ::   0%|                                   | 0/56 [00:00<?, ?it/s]

Refitting ..

procesing '['density', 'num_atoms']' with 'HOMO_energy' ... :: 100%|####################| 56/56 [01:00<00:00,  1.08s/it]

fitting has finished

procesing '['density', 'num_atoms', 'Mag']' with 'nelem' ... ::   0%|                            | 0/55 [00:00<?, ?it/s]

Refitting ..

procesing '['density', 'num_atoms', 'Mag']' with 'HOMO_energy' ... :: 100%|#############| 55/55 [01:05<00:00,  1.19s/it]

fitting has finished

procesing '['density', 'num_atoms', 'Mag', 'MagpieData mean GSmagmom']' with 'nelem' ... ::   0%| | 0/46 [00:00<?, ?it/s

Refitting ..

procesing '['density', 'num_atoms', 'Mag', 'MagpieData mean GSmagmom']' with 'HOMO_energy' ... :: 100%|#| 46/46 [01:00<0

fitting has finished

procesing '['density', 'num_atoms', 'Mag', 'MagpieData mean GSmagmom', 'MagpieData avg_dev CovalentRadius']' with 'Magpi

Refitting ..

procesing '['density', 'num_atoms', 'Mag', 'MagpieData mean GSmagmom', 'MagpieData avg_dev CovalentRadius']' with 'HOMO_

fitting has finished

procesing '['density', 'num_atoms', 'Mag', 'MagpieData mean GSmagmom', 'MagpieData avg_dev CovalentRadius', '7-norm']' w

Refitting ..

procesing '['density', 'num_atoms', 'Mag', 'MagpieData mean GSmagmom', 'MagpieData avg_dev CovalentRadius', '7-norm']' w

fitting has finished

procesing '['density', 'num_atoms', 'Mag', 'MagpieData mean GSmagmom', 'MagpieData avg_dev CovalentRadius', '7-norm', 'v

Refitting ..

procesing '['density', 'num_atoms', 'Mag', 'MagpieData mean GSmagmom', 'MagpieData avg_dev CovalentRadius', '7-norm', 'v

fitting has finished

procesing '['density', 'num_atoms', 'Mag', 'MagpieData mean GSmagmom', 'MagpieData avg_dev CovalentRadius', '7-norm', 'v

Refitting ..

procesing '['density', 'num_atoms', 'Mag', 'MagpieData mean GSmagmom', 'MagpieData avg_dev CovalentRadius', '7-norm', 'v

fitting has finished

procesing '['density', 'num_atoms', 'Mag', 'MagpieData mean GSmagmom', 'MagpieData avg_dev CovalentRadius', '7-norm', 'v

Refitting ..

procesing '['density', 'num_atoms', 'Mag', 'MagpieData mean GSmagmom', 'MagpieData avg_dev CovalentRadius', '7-norm', 'v

fitting has finished

In [20]:
Bestscoresatomic

{'RandomForest_atomic': [0.12470345167516507,
  0.10377461496994542,
  0.0802679090961164,
  0.079134002823931,
  0.07705401114045794,
  0.07975403723002375,
  0.07852459972140613,
  0.07896000175774369,
  0.07897724310419311,
  0.07860852714635881]}

In [21]:
Bestfeatsatomic

{'RandomForest_atomic': ['density',
  'num_atoms',
  'Mag',
  'MagpieData mean GSmagmom',
  'MagpieData avg_dev CovalentRadius',
  '7-norm',
  'vpa',
  'MagpieData mode NsValence',
  'packing fraction',
  'MagpieData avg_dev NpUnfilled']}

In [ ]:
model = RandomForestRegressor()

In [ ]:
model.fit(BS[components], BS['EF'])

In [ ]:
Ypredict = model.predict(BS[components])

In [ ]:
mean_squared_error(BS['EF'], Ypredict)

In [ ]:
%store  Bestfeatsatomic

In [ ]:
%store Bestscoresatomic

In [ ]:
CompositionFeatures

In [ ]:
AllFeatures.columns

In [ ]:
to_remove =  AllFeatures.columns.str.contains('Np|Nf|mode Number|mode Mendeleev|Row|mode Nd|mode')

In [ ]:
AllFeatures.drop(columns=AllFeatures.columns[to_remove],inplace=True)

In [ ]:
AllFeatures.columns

In [ ]:
model = RandomForestRegressor()

In [ ]:
model.fit(,BS['EF'].loc[AllFeatures.index])

In [ ]:
YPredict = model.predict(AllFeatures)

In [ ]:
mean_squared_error(BS['EF'].loc[AllFeatures.index], YPredict, squared=False)